# =============================================
# PROFIL : sender
# Role   : Programme 3 - Envoi vers API
# =============================================

# URL du backend API (profil api sur port 8080)
app.api.upload.url=http://localhost:8080/mp3/upload

# Pas de serveur web (ce programme envoie juste vers l'API)
spring.main.web-application-type=none

# Desactiver JPA (pas besoin de base de donnees)
spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
  org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
  org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration