# =============================================
# PROFIL : metadata
# Role   : Programme 2 - Extraction metadonnees
# =============================================

# Pas de serveur web (ce programme ecoute juste RabbitMQ)
spring.main.web-application-type=none

# Desactiver JPA (pas besoin de base de donnees)
spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
  org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
  org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration