# =============================================
# CONFIG COMMUNE A TOUS LES PROFILS
# =============================================

spring.application.name=mp3-backend

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/mp3db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Upload
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Stockage MP3
app.storage.path=storage

# Repertoire surveille par Programme 1
app.desktop.watch.path=C:/Users/miari/Documents/projetMP3/mp3/musique

# Logs
logging.level.org.springframework=INFO
logging.level.com.mp3.demo=DEBUG